services:
  bot:
    build: .
    container_name: po-signals-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_FILE=/app/data/signalsbot.db
    volumes:
      - ./data:/app/data